### ISSUE TITLE
Knob grouping

### ISSUE THREAD

**Issue by pollend** [Baste-RainGames/Node_Editor#100]
It would be nice to able to create subgroups of knobs. I've abstracted this out on my end but it would be a nice feature to see in a future release of the library.

![image](https://cloud.githubusercontent.com/assets/854359/18813129/ad577754-82a1-11e6-9e87-5ed5cc33ca64.png)

**Comment by Seneral** [comment]
Just to be sure, what would these subgroups be for? Visual grouping of normal knobs, or do they have their dedicated structure/API?
If it's the first, it wouldn't need structural grouping, a function to draw knob x-y together would suffice, right?
Also, if you feel comfortable don't hesitate to make a PR with your work on this;)

**Comment by pollend** [comment]
So the way you restore canvases is to duplicate all objects and this ends up breaking any references to that knob. It would be nice to subgroup nodes so you only have to track the subgroups of knobs rather then the entire set. It's not too bad to work around this limitation but its pretty fiddly.

**Comment by Seneral** [comment]
Oh, so there's actually a better way to approach this problem. I'm imagining attributes to tag these references and then restoring those are automatically handled.
Also, reminds me of #91 ;)
I'll adress this Problem soon!
