### ISSUE TITLE
Lacking CurveField in RTEditorGUI

### ISSUE THREAD

**Issue by Craftomega** [Baste-RainGames/Node_Editor#102]
I was attempting to create a curve field in RTEditorGUI the issue is I have no idea on how to get keys and the like.

Could this be implemented?

**Comment by Seneral** [comment]
It has already been done, but there's no open source implementation afaik:(

The class [AnimationCurve](https://docs.unity3d.com/ScriptReference/AnimationCurve.html) does provide almost everything data-wise fortunately. So the hardest part is the GUI, but it's definitely possible. The biggest issue I see, the runtime bezier drawing, is already used in the Node Editor Framework...
Don't hesitate to try and implement this:)

**Comment by Seneral** [comment]
I'll close this for now, as I personally won't implement this, but if anyone wants, there's no problem with that:)
