### ISSUE TITLE
[Feature Request] Input Control Toggle

### ISSUE THREAD

**Issue by m9731526** [Baste-RainGames/Node_Editor#103]
For long input situations like dialog creation, Moving nodes with arrow keys could be annoying when users try to move input cursor back and forth to edit the content typed in, especially for non-English language such as Chinese, as the input methods are different from English input method (a press for a alphabet).

I suggest add a toggle on sidebar to enable/disable the input control system.

**Comment by Seneral** [comment]
Thanks for the report! But it's possible to approach it better. I'll create a fix so the keyboard movements in the input systems are not regarded when there's an input field activated. Would that be sufficient?
