### ISSUE TITLE
Windows Store support

### ISSUE THREAD

**Issue by logangorence** [Baste-RainGames/Node_Editor#105]
Is there a possibility to create a Windows Store compatible version of this library? There are various errors throughout the project, due to the Windows Store runtime not being the same as the standard Unity one.
Some of the errors include things such as Type missing multiple functions, as well as Assembly.

**Comment by Seneral** [comment]
I'll take a look at it, but currently do not have Windows build support store installed.
Do these errors fall under [these missing types](https://docs.unity3d.com/Manual/windowsstore-missingtypes.html)?

**Comment by Seneral** [comment]
Just downloaded and realised I need windows 8 for it to test...
So I'll somehow need to test it on my tablet pc, tomorrow. If you can give me more information about these errors earlier I might be able to take a look at it today:)

**Comment by logangorence** [comment]
Hi, the problems I was running into were just random things that aren't available from the Type and Assembly classes that are part of the base library(this made up most of the issues). I assume this is due to the base library being .NET Core.

**Comment by Seneral** [comment]
Can you give me a screenshot or copy of all the errors?

**Comment by Seneral** [comment]
This line in the page linked above adresses missing functions on System.Type:
`WinRTLegacy.TypeExtensions has methods GetConstructor(), GetMethod(), GetProperty() for System.Type`

**Comment by logangorence** [comment]
Here's a Gist that contains the errors I'm having https://gist.github.com/logangorence/3ea0dd9e2aed5b9482002c6c566b14dd

**Comment by Seneral** [comment]
Ok just finished installing on tablet PC, sorry it did take so long. But looking at the errors there are chances I am able to replace the missing functions, but not every single one is provided by Unity as a replacement, so it might get tricky...

**Comment by logangorence** [comment]
Sounds great, if you could keep this issue updated, that would be amazing.

Thanks for the help so far. If you have anything I can assist with, just let me know.

**Comment by Seneral** [comment]
Sorry I've a hard time getting my test rig to work. Bunch of stuff to download and install for that on my crappy tablet PC, even fighting with hard disk space lol...
Will update as soon as I can get the build support to work.

**Comment by Seneral** [comment]
Ok, so I gave up on setting up the test rig. Even after deleting various old programs and old unity versions, I can't cramp a seven gigs VS upate on one GB free space. And Unity's still throwing errors on wrongly installed SDK which I can't figure out. Also find that I can't access WinRTLegacy without all that so I currently have no way of fixing these errors, sadly, as there is no real doc on WinRTLegacy.

Best bet for you is taking a look into that yourself:/ Basically, [this page](https://docs.unity3d.com/Manual/windowsstore-missingtypes.html) is everything needed. It's just that some functions are not available in _System.Type_, and _WinRTLegacy.TypeExtensions_ seems like the solution for most.
Please tell me if that would work. Thanks you!

**Comment by Seneral** [comment]
Again, I need your help fixing that problem... Just reopen if you want:)
