### ISSUE TITLE
Can not build project with the node editor

### ISSUE THREAD

**Issue by NiloFV** [Baste-RainGames/Node_Editor#108]
Get the error on build: **Error building Player because scripts had compiler errors**
I know it is something about UnityEditor dependencies, that we have to wrap between #if UNITY_EDITOR #endif. But i search the whole code and could not find the breaking point.

**Comment by NiloFV** [comment]
When do you try to build it actually tells you con the console log where these errors are... will fix the main branch and make a push request... :)

**Comment by Seneral** [comment]
Thanks for the report, very much appreciate your effort! :)
Fixed it both for the master and develop branch.
