### ISSUE TITLE
Scene was not marked as dirty when "Save to Scene" pressed in NodeCanvas

### ISSUE THREAD

**Issue by kalinarm** [Baste-RainGames/Node_Editor#113]
and cannot be saved without another modification in scene.
I think it can be done by using https://docs.unity3d.com/ScriptReference/Undo.RecordObject.html as this function is recquired only into editor

Keep up this really great job !

**Comment by Seneral** [comment]
Thanks for the report, will add this tomorrow:)
Actually, there's S[ceneManagement.EditorSceneManager.MarkSceneDirty](https://docs.unity3d.com/ScriptReference/SceneManagement.EditorSceneManager.MarkSceneDirty.html) and for older versions [EditorApplication.MarkSceneDirty](https://docs.unity3d.com/ScriptReference/EditorApplication.MarkSceneDirty.html) ;)

**Comment by Seneral** [comment]
That should do it:)
