### ISSUE TITLE
Using arrow keys when in input field has focus moves the whole node.

### ISSUE THREAD

**Issue by virror** [Baste-RainGames/Node_Editor#114]
Using arrow keys when in input field has focus moves the whole node, would be nice if this only happened when the focus was on the node itself, and not a field on it.

**Comment by Seneral** [comment]
Fixed that in 25f0e1a already, but it's only on develop so far, as it is not that critical to directly push to master. If you want, you can add the few lines manually until we merge it:)

**Comment by virror** [comment]
Ok!
