### ISSUE TITLE
Infinite Loop in ClearCalculation Function

### ISSUE THREAD

**Issue by omid3098** [Baste-RainGames/Node_Editor#14]
Unity version: 5.2.1f1

If you make two recursive node (node.allowRecursion = true) and loop them, it will make an infinite loop in ClearCalculation Function in NodeEditor Class and unity will shut down without any log.

this loop is made in NodeEditor.cs:848

**Comment by omid3098** [comment]
this fixed problem for me (NodeEditor.cs:848):
if (!node.allowRecursion) ClearCalculation (output.connections [conCnt].body);

**Comment by Seneral** [comment]
Thanks for the report, I initially handled such problems with the node.shouldCalculate bool (like in the AllAroundNode Test node). The case allowRecursion = true and shouldCalculate = true was thought for the node itself to handle in the Calculation function. Though it seems I missed to handle that case in ClearCalculation:( Recursion is a bit tricky, and I should definitely rework how it's handled to prevent such crashed...

**Comment by omid3098** [comment]
My nodes already have allowRecursion and the reason I cant use shouldCalculate is that I need my nodes to calculate and update values with  any connection change.
Thanks for your respond.

**Comment by Seneral** [comment]
My latest commit (2dd6eb8a3e49fe9e1853685282cac4d98dd06522) adresses this and some minor othr problem, be sure to check it out;) The Recursive system is now totally secure, even if you chose allowRecursion = true and shouldCalculate = true
