### ISSUE TITLE
Android Build

### ISSUE THREAD

**Issue by omid3098** [Baste-RainGames/Node_Editor#15]
When I try to build for android, these two error happens:

```Assets/Plugins/Node_Editor/Framework/NodeEditor.cs(891,54): error CS0234: The type or namespace name `LoadAll' does not exist in the namespace `NodeEditorFramework.Resources'. Are you missing an assembly reference?```

```Assets/Plugins/Node_Editor/Framework/NodeEditor.cs(946,29): error CS0165: Use of unassigned local variable `objects'```

also tried with blank project and the same error happens.

**Comment by Seneral** [comment]
Hi,
I fixed that in this commit 1d7323c082704b86e15e904fb73bcb8a000e081e . Seems as if the compiler of the editor recognises if I assign a variable in an else block (so all variables where definitely assigned), while the build compiler doesn't... And I didn't noticed the first error as it was inside an editor precompiler block which broke after I added a sub-namespace called Resources ....

Hope it works for you now, be sure to tell if it works on android:) 
I suppose you're using a tablet, for smartphone the screen would be just too small... I already tested it successfully on a windows tablet, touch controls do work pretty well;)
