### ISSUE TITLE
Save As can generate invalid paths

### ISSUE THREAD

**Issue by metzsg** [Baste-RainGames/Node_Editor#157]
When the user chooses "Save As" on a canvas that already has a savePath, the full savePath is given to UnityEditor's SaveFilePanellnProject as its starting path.  If the user specifies a different name without changing directories, that name is added to the end of the full savePath (including original asset name), generating an exception when unity attempts to write to the path.  It seems like SaveFileInPath expects only a directory as the path parameter.

I've solved by parsing the savePath a bit before input into SaveFilePanelInProject:

```
private void SaveCanvasAs()
{
    string panelPath = NodeEditor.editorPath + "Resources/Saves/";
    string panelFileName = "Node Canvas";
    if (canvasCache.nodeCanvas != null && !string.IsNullOrEmpty(canvasCache.nodeCanvas.savePath))
    {
        panelPath = canvasCache.nodeCanvas.savePath;
        string savedFileName = System.IO.Path.GetFileNameWithoutExtension(panelPath);
        if (!string.IsNullOrEmpty(savedFileName))
        {
            panelPath = panelPath.Substring(0, panelPath.LastIndexOf(savedFileName));
            panelFileName = savedFileName;
        }
    }
    string path = UnityEditor.EditorUtility.SaveFilePanelInProject("Save Node Canvas", panelFileName, "asset", "", panelPath);
    if (!string.IsNullOrEmpty(path))
        canvasCache.SaveNodeCanvas(path);
}
```

**Comment by Seneral** [comment]
Thanks, will include it. Somehow forgot about it:)

**Comment by Seneral** [comment]
Sorry for the immense delay. Just merged it
