### ISSUE TITLE
Make NodeEditorSaveManager.CreateWorkingCopy() Work at runtime. 

### ISSUE THREAD

**Issue by jangofett890** [Baste-RainGames/Node_Editor#160]
I needed to create an instance of a slightly modified DialogNodeCanvas for my game, and I tried using UnityEngine.Object.Instantiate but it only made a new Canvas and the nodes were still a reference.

I found out about NodeEditorSaveManager.CreateWorkingCopy() and it would not execute at runtime because the dictionaries of NodeTypes and NodePortDeclerations were empty. I fixed this by calling their two recalculate functions in CreateWorkingCopy().

The new code:
 `

           public static NodeCanvas CreateWorkingCopy (NodeCanvas nodeCanvas, bool editorStates = true) 
            {
            if (nodeCanvas == null) {
                return null;
            }

            NodeTypes.FetchNodeTypes();
            ConnectionPortManager.FetchNodeConnectionDeclarations();
            //.... Cut code here
`

**Comment by Seneral** [comment]
Sorry for the late answer. Although not explicitly stated, the framework generally expects a call to NodeEditor.checkInit before usage. If you only use stuff like that, you can just pass false, which will init the base modules.
If you want to use GUI parts of the framework, call this additionally with parameter true from a GUI function (!) and it will init the GUI-related modules.
Hope that helps!
