### ISSUE TITLE
In Unity 2018.2.0b1, GUIScaleUtility no longer has access to UnityEngine.GUIClip.

### ISSUE THREAD

**Issue by snorthman** [Baste-RainGames/Node_Editor#161]
The editor does not work in the new 2018 (beta) version, but I've only just found this framework so I can't help any further.

**Comment by Seneral** [comment]
Will take a look, thanks! There have been rare occasions before (mac mostly, if I remember correctly) where there were problems, maybe it's that again. Guess they either fixed the GUI scale completely so this workaround is not needed (too good to be true) or they broke the only real workaround ... lets hope for the best:)

**Comment by Seneral** [comment]
Ya, could reproduce it, seems they changed a bit. They changed from internal class public members to internal class internal members. Easy to adapt in principle. Have a fix ready I think:)

**Comment by Seneral** [comment]
Should be fixed in d4b6084 :)
