### ISSUE TITLE
Error: Random.InitState(seed) is not allowed in ScripatableObject's Contructor

### ISSUE THREAD

**Issue by No3371** [Baste-RainGames/Node_Editor#163]
This happens when I try to use a ValueConnectionKnobStyle with Type parameter on dynamicConnectionPort. (I have not tested it on static ports)

```CSharp
private ValueConnectionKnobAttribute optionconditionAttr 
	= new ValueConnectionKnobAttribute("Show?", Direction.In, typeof(bool), ConnectionCount.Single, NodeSide.Left);
```

And if I try to use "Bool" parameter the result knob texture would be totally white. (Failed to create the style)

**Comment by Seneral** [comment]
Hm will have to take a closer look later, but never seen this before.
It's only for color generation for new types that do not have a style definition somewhere in the project though... Should be some workaround.
If you want to get going quickly, I recommend to just create style definitions with predefined colors for each style! For that, take reference from the [default float connection type](https://github.com/Seneral/Node_Editor_Framework/blob/develop/Node_Editor/Default/Calculation%20Base/FloatCalculation.cs).
