### ISSUE TITLE
Node Port GetConnectedChildren generates garbage

### ISSUE THREAD

**Issue by lucasmontec** [Baste-RainGames/Node_Editor#168]
It instantiates a list every call, that can be changed to just clear a list.

`public List<Node> GetConnectedChildren() {
            children.Clear();
            foreach (var cnn in connections) {
                children.Add(cnn.node);
            }
            return children;
        }`

**Comment by SlimeQ** [comment]
Where is this located? I can't find such a function anywhere in the code base
