### ISSUE TITLE
RT Node Editor - enum not visible

### ISSUE THREAD

**Issue by karadagi** [Baste-RainGames/Node_Editor#171]
Hi everyone,

I have just started to use Node_Editor. The real-time node editor is very promising however enum options in the CalcNode is disabled. On the other hand, It's selectable in the normal editor (not the RT).

**Comment by karadagi** [comment]
Hi,

is there anybody to reply?

Maybe I was not clear. The problem is selecting basic mathematical expressions from the calcNode component in runtime. The enum options are not shown as drop down. The “add” expression is default and the user cannot select a different option like “multiply” or “divide” at runtime.

**Comment by Seneral** [comment]
Sorry, I did not receive any notifications recently from github!
Ya, the popup is an editor-only control (UnityEditor namespace) and as such can't be used at runtime. Only way around this is to implement an own popup control, which is partly done for context clicks already and could be extended to enum popups aswell... You can have a look at OverlayGUI if you want to have a look at that (or find an existing popup solution working in IMGUI, NOT the new GUI).
