### ISSUE TITLE
the look the node  change when drag the graph in a monitor main or external

### ISSUE THREAD

**Issue by gtoto007** [Baste-RainGames/Node_Editor#172]
I did git clone on branch develop but I have problem with the look of nodes

If I have the graph node editor  on monitor external the look of node seems correct

![schermata 2018-11-08 alle 22 58 38](https://user-images.githubusercontent.com/6715157/48230124-4072a200-e3aa-11e8-978f-5a6d92dc9c32.png)

If I have the graph node editor on main monitor the look of node is busted 
<img width="1680" alt="schermata 2018-11-08 alle 22 58 52" src="https://user-images.githubusercontent.com/6715157/48230137-4d8f9100-e3aa-11e8-8bbd-776722880c85.png">

Information:
Unity 2018.2.14f1
Mac Hight Sierra
Mac Book Pro late 2016

**Comment by gtoto007** [comment]
I tested this issue on Window and it do not occur. Only Mac.

**Comment by Seneral** [comment]
Can any mac user check if this is still a Problem?
Changed the way GUI works and also some texture's import settings recently.
