### ISSUE TITLE
Knob aspect ratio is wrong for non-square knob graphics.

### ISSUE THREAD

**Issue by xyzDave** [Baste-RainGames/Node_Editor#174]
I've been playing with the framework and swapped the knob graphics.
The non-square graphics I used were not rendered with the correct aspect ratio which revealed two possible bugs:
1. in ConnectionKnob.cs
	_private float knobAspect { get { return knobTexture != null? knobTexture.width/ knobTexture.height : 1; } }_
The line should be changed to:
	_private float knobAspect { get { return knobTexture != null? **(float)** knobTexture.width/ **(float)** knobTexture.height : 1; } }_
	The knobTexture.width and height need to be case to a float or the result otherwise the result is the result of dividing the two as integers (i.e. 48/30 would produce 1 not 1.6)

2. in ConnectionKnob.cs
In GetCanvasSpaceKnob, the calculation appears to be wrong.
Currently it is:
 _Vector2 knobSize = new Vector2 (NodeEditorGUI.knobSize * knobAspect,										 
                                         NodeEditorGUI.knobSize / knobAspect );_
 This should be changed to:
 _Vector2 knobSize = new Vector2 (NodeEditorGUI.knobSize * knobAspect,										 
                                           NodeEditorGUI.knobSize  );_
(The **"/knobAspect"** removed)
The aspect ratio value calculated here is used to multiply the horizontal to scale it up to keep the ratio correct for the vertical (to make sure the vertical is no bigger than "knobSize"), or divide the vertical by the aspect ratio to make sure the horizontal is no bigger than "knobSize", there is no need to do both.

I've tried it and it appears correct, so thought I'd add it as an issue.
Cheers,
xyzDave

**Comment by Seneral** [comment]
Sorry for the super late reply.
Have included both fixes.
