### ISSUE TITLE
How to get the canvas to run at Runtime?

### ISSUE THREAD

**Issue by oxi-dev0** [Baste-RainGames/Node_Editor#177]
I cannot find how to run the canvas at Runtime, I am making a Behaviour Tree type thing. I need it to run my nodes at runtime. Any help would be apprieciated, Thanks, X0FloH

**Comment by Seneral** [comment]
Sorry for the late reply. Usually this works by implementing a canvas traversal algorithm for your behaviours. A behaviour-tree type traversal isn't included by default, but it should be no big deal. You might also want to check out the property 'AllowRecursion' on you behaviour nodes, but your traversal algorithm needs to handle this.
Check out the [default traversal implementation ](https://github.com/Seneral/Node_Editor_Framework/blob/develop/Node_Editor/Default/Calculation%20Base/CanvasCalculator.cs)for reference.
