### ISSUE TITLE
GUIScaleUtility.cs Init Method NullReferenceException in Unity 2019.1.2f1

### ISSUE THREAD

**Issue by Kaorixsol** [Baste-RainGames/Node_Editor#182]
I am trying to use Node_Editor in Unity2019.1.2f1，
When I open the Node Editor, it always report a Null Error.
I found that in the Init function in the GUIScaleUtility script, the topmostRect variable is empty, and its GetGetMethod returns null.

topmostRect is private in Unity 2019.1.2f1.
it should be :
`PropertyInfo topmostRect = GUIClipType.GetProperty ("topmostRect", BindingFlags.Static | BindingFlags.NonPublic);`

`topmostRectDelegate = (Func<Rect>)Delegate.CreateDelegate (typeof(Func<Rect>), topmostRect.GetGetMethod (true));`

**Comment by Seneral** [comment]
Will download 2019 now and test, but topmostRect is already searched using Public | NonPublic which should include both.

**Comment by Seneral** [comment]
Ok in the latest version it works fine, and the changes you propose are already there (+backwards compability), so you might be using an older version I assume?

**Comment by Kaorixsol** [comment]
I haven't tested it with another version, just in Unity2019.1.2f1, I tested other versions.

**Comment by Kaorixsol** [comment]
I still have this problem on Unity2019.1.12f1. I have not installed the updated version locally. Do you need me to help with more tests?

**Comment by Kaorixsol** [comment]
![image](https://user-images.githubusercontent.com/20392465/63342402-f9283180-c37d-11e9-8b91-7e11d567bfa9.png)

**Comment by Seneral** [comment]
But are you using the latest version of the Framework from the develop branch? 
These are the most current lines from the develop branch and they should work just fine on your system if the lines your provide work:

PropertyInfo topmostRect = GUIClipType.GetProperty ("topmostRect", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic);
// ERROR

MethodInfo GetTopmostRect = topmostRect != null? (topmostRect.GetGetMethod(false) ?? topmostRect.GetGetMethod(true)) : null;

topmostRectDelegate = (Func<Rect>)Delegate.CreateDelegate (typeof(Func<Rect>), GetTopmostRect);

**Comment by Seneral** [comment]
And are you on Mac by any chance? The 'comability mode' was initially introduced because some Mac users had similar problems, but I've never been able to debug them properly
It works fine on 2019.1.14f1 on Linux

**Comment by Kaorixsol** [comment]
Sorry, I am using the code of the master branch, I switch the branch.

**Comment by Kaorixsol** [comment]
No problem, it’s my negligence, sorry again, respected author

**Comment by Seneral** [comment]
Ah ok, is there any reason for that? Made the develop branch the default, master hasn't been updated in ages now. I currently don't have enough time to keep it updated regularily with fixes.
Cool, no problem, glad it works now!
