### ISSUE TITLE
How to input multiple outputs to a node?

### ISSUE THREAD

**Issue by Ragueel** [Baste-RainGames/Node_Editor#193]
I have been trying to create some sort of level editor which will contain how the level would be created. For example, there would `LevelRootNode` which will take as input several `WaveNode` maybe something like `List<WaveNode>`. `WaveNode` will also input many `EnemyNode` something like `List<EnemyNode>`. I didn't found any docs about that so I need some help with how can I do something like that.

**Comment by Ragueel** [comment]
Here is what I mean:
![image](https://user-images.githubusercontent.com/28916549/90310734-2f0ee000-df16-11ea-83e3-851442a9fe6b.png)

**Comment by Seneral** [comment]
You need to setup the knobs so you can connect them, and there are several ways you could go about it.
If you have some data you want to pass along, you could create a WaveData and EnemyData type connection for the respective input and output knobs. If you only care about tr fact that they are conmected, you can create knobs which don't pass data (See Flow Node example) - only a semantic difference.

Unfortunately currently the UI editing doesn't allow true multi-multi connections (see #149), so if you want to have multiple inputs to a knob, the output you want to connect them to need to be limited to one output connection. This might even be desirable in your case. If it causes a problem however, as a workaround you can manually create more input knobs as you add inputs (see Resizing Node example), however that's a bit of work, so if you can avoid it, try to.
Hope that helps

**Comment by Ragueel** [comment]
Thanks for your explanation. I was able to figure out how some parts work but I didn't get the idea how can I pass data.
![image](https://user-images.githubusercontent.com/28916549/90314780-3f37b700-df38-11ea-9791-a56a7071a87f.png)
This is something that looks similar to what I wanted to achieve.  Could you give a simple example with `EnemyData` because what I am thinking probably is a bit stupid. 

So to connect `EnemyNode` with `WaveNode`, I created the class 
```
public class EnemyNodeConnectionType : ValueConnectionType
    {
        public override Type Type => typeof(EnemyNode);
        public override string Identifier => "EnemyNode";
        public override Color Color => Color.blue; // Color didn't change in the editor
    }
```
I connected it in `EnemyNode` with:
``` 
[ValueConnectionKnob("EnemyInfo", Direction.Out, typeof(EnemyNodeConnectionType))]
public ValueConnectionKnob enemyOut;
```
And in `WaveNode` I did:
```
[ValueConnectionKnob("Enemies", Direction.In, typeof(EnemyNodeConnectionType), ConnectionCount.Multi)]
public ValueConnectionKnob waveIn;        
```
I don't think I have anything that needs to be calculated, I only need some sort of data flow so I can create enemies and waves. To do that I was thinking of using maybe `inputPorts` inside `Node` class. 😃

**Comment by Seneral** [comment]
Take a look at the example nodes, especially the [FloatCalculation](https://github.com/Seneral/Node_Editor_Framework/blob/develop/Examples/FloatCalculation/CalcNode.cs#L18) one.
the Type overload for `ValueConnectionKnob `is only used for when you did NOT explicitly create a `ValueConnectionType` - it will take the type and generate a color for it, for quick prototyping. Since you did create an explicit type, replace the third parameter with the identifier you specified, `"EnemyNode"`.
However, seeing you specified `typeof(EnemyNode)` as the type of data you want the connection to pass, it looks like you only want to create a connection with two nodes, but don't care about actually passing data through it. So you could use a normal `ConnectionKnob` (without value), like in the [Flow node example](https://github.com/Seneral/Node_Editor_Framework/blob/develop/Examples/Nodes/FlowNode.cs#L16). This will still give the node information about the nodes it is connected to, which I believe is what you want.

**Comment by Ragueel** [comment]
Ahh, I finally get it. Thanks for the help. 👍 
So far node editor looks really good. Is there way to make background dark? :)

**Comment by Seneral** [comment]
Are you perhaps on a Mac? Thought you changed the look intentionally at first, but there was a perhaps related issue before (#172) however I could not reproduce it.
Can you play with the texture import settings and see if you can get it to look like in the [title image](https://github.com/Seneral/Node_Editor_Framework#readme)? If you could get it to work I could figure out if and which import settings cause this.

**Comment by Ragueel** [comment]
I checked textures they seem to be gray. 

![image](https://user-images.githubusercontent.com/28916549/90318910-88e2ca80-df55-11ea-8926-314b8ccaeb0a.png)

The strange thing is that they have normal color when I view it outside the unity
![image](https://user-images.githubusercontent.com/28916549/90319037-803ec400-df56-11ea-916e-6119a197171e.png)

After setting sRGB texture now it appears to be normal color.

![image](https://user-images.githubusercontent.com/28916549/90319084-c431c900-df56-11ea-9319-b468e5a8de7d.png)


Full settings of the image:
![image](https://user-images.githubusercontent.com/28916549/90319104-fd6a3900-df56-11ea-8cdc-ce8784749f29.png)


I can create pull request with it if you want.

**Comment by Seneral** [comment]
That looks good, thank you alot. Will probably have to change the metadata in an earlier version of unity so that they are still supported. Can do that next update
