### ISSUE TITLE
Apple M1 computers not displaying Bezier curves

### ISSUE THREAD

**Issue by Scottrps** [Baste-RainGames/Node_Editor#195]
The new apple silicon does not appear to display the Bezier curves at runtime (they are visible in webGl on the same system)
Intel chips work fine with the same install file.

I've tried Unity 2020.1 and 2020.2 with a general build and a targeted M1 build, all builds fail to display the curves (haven't tried linear) 

It does appear that the actual connections are being made and the calculations are being done its just the display itself that is not working

**Comment by Seneral** [comment]
OK so there's no way I'll be able to test this, but I assume it's unity shaders not being fully supported yet. The lines are using a custom line shader:
https://github.com/Seneral/Node_Editor_Framework/blob/develop/Node_Editor_Framework/Runtime/Resources/Shader/LineShader.shader
 I guess you could try modifying it a bit or looking into newer unity built-in GUI shaders to see if they changed anything to make them work on M1. This shader I think I adapted from the 5.6 builtin GUI shaders, so a long while ago.

**Comment by Scottrps** [comment]
just checked that using the default unlit/color shader, sadly the same result.  good on intel, not on apple

I'm using GL draw in other situations and I'm not seeing any issues,

**Comment by Scottrps** [comment]
Following up on this, it appears that Unity have fixed this issue.
