### ISSUE TITLE
Memory leak when opening a canvas

### ISSUE THREAD

**Issue by pmhpereira** [Baste-RainGames/Node_Editor#25]
Loading a file in the editor and moving the canvas around will result in a large increase of memory usage over time, where only a fraction of it is GC'ed. Unity must be restarted to clear the used memory.

Loading a file in the runtime editor will have the same effect.

This doesn't happen (at least as badly) when there aren't nodes in the canvas.

**Comment by Seneral** [comment]
Thanks, just took a look and indeed, only when dragging around (or, as is my assumption, when calling OnGUI), I have some severe memory leaks of around 50MB/second... I have to take a look, thanks very much for reporting this!

**Comment by pmhpereira** [comment]
I'm trying to find the culprit and it seems to be related to `DrawConnections()`.

**Comment by pmhpereira** [comment]
Just a funny story to justify this finding: I noticed this when I was demoing my thesis to my supervisor (I use this project as a manager for specifying some rules to the creation/generation of obstacles in my platformer game) and after 5 minutes Windows crashed, straight to the log-in screen. :-)

**Comment by Seneral** [comment]
Yes, you're right, seems to be it;) You're pretty fast, was about to download a leak tracker lol...
Anyway, then I'm assuming it's the drawing formula I'm using or how the textures are handled...

**Comment by Seneral** [comment]
It is my drawing formula. Adding 
'''C#
UnityEditor.Handles.DrawBezier (startPos, endPos, startTan, endTan, col, tex, width);
return;
'''
in the RTEditorGUI.DrawBezier function, before my implementation, fixes it. I'll examine this more closely and report asap:)

**Comment by pmhpereira** [comment]
Found it!
    
    // NodeEditorGUI.cs:125
    Material mat = new Material (Shader.Find ("Unlit/Transparent"));
    mat.SetTexture ("_MainTex", tex);
    mat.SetPass (0);

**Comment by Seneral** [comment]
It is, problem fixed, thank you:)


Wow, really?! I hope that didn't ruin your thesis :( That would be absolutely desastrous:(

**Comment by Seneral** [comment]
Don't understand though why the GC didn't clean up... Maybe to much garbage too fast.... lol

**Comment by pmhpereira** [comment]
I was just showing the progress I made since the last meeting we had. It was cool to see Windows spasming and flashing my screen like crazy before exiting my user session. :D

Are you fixing it, or want me to make a PR?

**Comment by Seneral** [comment]
Already fixed, I was onto finishing the update anyway:)

**Comment by pmhpereira** [comment]
Thanks for looking into this so quickly. ;-)
If you had taken more 15 min to answer, I would had fixed it myself. :P
