### ISSUE TITLE
Node Areas / Groups

### ISSUE THREAD

**Issue by Seneral** [Baste-RainGames/Node_Editor#41]
**Description:** Ability to group nodes in an area (maybe just colored rect with a header). Nodes that are inside this area are automatically attached, This group can be picked and moved around, together with the nodes, and also resized. Using a button in the header, title and color can be edited. If deleted, the nodes inside are untouched.

**State:** Petty much done, resizing is supported, color and title can be edited, dragging groups moves also all pinned nodes and subgroups (recursively). All stuff around it is also pretty stable (input, saving, etc.)

References from Substance Designer:
![image](https://cloud.githubusercontent.com/assets/12800840/13154493/7f8e83f0-d679-11e5-849b-877850da73a8.png)
![image](https://cloud.githubusercontent.com/assets/12800840/13154512/8dc38d26-d679-11e5-85a3-99232bf77bae.png)

**Comment by Seneral** [comment]
Aishiteru on the Unit forums and me are working this out (along with the input system). It's working out pretty well and we're using this also as a test on how difficult it is to implement custom elements/controls...

**Comment by rudinesurya** [comment]
I think the node group should be able to drag another node group that is fully contained within the bigger rect. I found a bug, the focusing does not work properly with the node groups. I will try to fix that when i have time to look at the codes =)

![123123](https://cloud.githubusercontent.com/assets/8660021/14131534/cf305e5a-f66e-11e5-9fd5-26adafac2d07.png)

**Comment by Seneral** [comment]
Oh, of course! :D
That could look like this:
1. Sort group by their size (low-high), handle following steps foreach group in that order:
2. update pinned nodes, avoid nodes that are already pinned by smaller groups (potential subgroups)
3. check if the group is focused
  -> not only drag the group and it pinned ndes, but all pinned subgroups
  -> abort process, so only the smallest group that was focused (current) is dragged
What do you think?
Only theory so far, I'm unable to implement until friday evening. If you want, you can do this:)

**Comment by rudinesurya** [comment]
i was thinking of a simpler way, does not need to be recursive at all. Just get all the nodes and node groups contained in the selected node group. The sorting seems like an excellent idea, but I wont have time to touch on this till next week.

**Comment by Seneral** [comment]
You have to account for the nodes pinned on subgroups that are no directly inside the focused group, too. Because of that it's even simpler to make it recursive. You could of course make it linear, but it really is the best that way I think:) I now have some time to do this so I can post something soon!

**Comment by Seneral** [comment]
Sorry for the long periode of silence from my side, I have been very busy:/
Anyway, it's better now, so in 5f1dc03 I implemented the idea posted above and the groups feature is in a pretty decent state now I think:)
Thanks @rudinesurya :)

**Comment by rudinesurya** [comment]
hey. i have been quite busy, i think you should merge it first then it will be easier for me to pull a fresh copy and see what else i can add on.

**Comment by Seneral** [comment]
Any updates @rudinesurya ? Or I'll just close it here and now, cause you can commit an update later on without a problem:)

**Comment by rudinesurya** [comment]
hi, have you merged it yet ? sorry for the silence, too busy looking for job and being nationless makes it even harder =(

**Comment by Seneral** [comment]
Oh, I'm very sorry to hear that (the nationless part, that is). Wish you best luck! :)

I did not merged it yet because it needs some manual work I have to resolve when I have time:)

**Comment by Seneral** [comment]
For the record, [this is the branch](https://github.com/Baste-RainGames/Node_Editor/tree/feature/Groups) for the groups feature. Unless anyone has further suggestions I would merge it as soon as I have time.

**Comment by Seneral** [comment]
This has been implemented in 1a2fee1, but there's always space for improvement. Especially as there is a small problem with snapping and groups right now, so I'll leave this issue open;)
Sorry it took me so long to merge!

**Comment by Seneral** [comment]
Will close this off for now!
