### ISSUE TITLE
Clipping for custom runtime Bezier drawing

### ISSUE THREAD

**Issue by Seneral** [Baste-RainGames/Node_Editor#44]
**Description:** As handles cannot be used at runtime, I created a bezier drawing function some time ago. It works but currently does not provide clipping (not only for optimisation, but it will extend over bounds).

**State:** None. To get the bounds to clip to, use GUIScalingUtility.cs, there are properties to get the parent group rect.

**Location:** RTEditorGUI.cs

**Comment by pmhpereira** [comment]
I'll tackle this. :+1:

**Comment by Seneral** [comment]
Very nice, thanks! :)

**Comment by Seneral** [comment]
Finally implemented it in a85636a:)
