### ISSUE TITLE
Node Properties Display Within Side Window Of NodeEditorWindow

### ISSUE THREAD

**Issue by ScriptGeek** [Baste-RainGames/Node_Editor#45]
Optional feature that allows users of the framework to create their own custom GUI editor that will be drawn inside the side window of the NodeEditorWindow.

**Comment by pmhpereira** [comment]
I'd like this too. One of the main reasons I think this makes sense is because as the list of different node types increase, the contextual menu will become more and more complicated to navigate.

Allowing to override the right GUI part of the NodeEditor would allow to have something like a drag-and-drop of nodes and should be the window where each node properties are displayed when selected (instead of the Inspector window).

**Comment by ScriptGeek** [comment]
I managed to implement this feature with a bug concerning IMGUI elements on my fork repo:
https://github.com/ScriptGeek/Node_Editor

Bug: Throws an exception when clicking on the node that implements this feature:
ArgumentException: Getting control 8's position in a group with only 8 controls when doing mouseDown

Somehow the number of GUI elements changes between the Layout and Repaint events.  It was tested using this code as the override method:

public override void DrawNodePropertyEditor()
{
        name = GUILayout.TextField(name);
}

How to resolve this problem?

**Comment by pmhpereira** [comment]
Try:

	if (Event.current.type != EventType.Repaint)
		return;

**Comment by ScriptGeek** [comment]
I found a solution to the issue...

The event that was causing the issue was EventType.Ignore, so avoiding the call to the DrawNodePropertyEditor method when this event type is the current event results in the exception no longer being thrown.

**Comment by pmhpereira** [comment]
:+1:

**Comment by Seneral** [comment]
Cool, can you create a pull request for this?

**Comment by ScriptGeek** [comment]
I had in my mind that NodeGUI and DrawNodePropertyEditor were for separate purposes.  NodeGUI being better suited for displaying flow control info so that a quick glance at the node graph conveniently indicates key info about the relationships between nodes; for example, displaying the current node state in a state machine.  DrawNodePropertyEditor being better able to display the node properties in much more detail; for example, displaying an overabundance of details that would not fit inside the node's graphical area.  Using both methods allows for the leveraging of each of their advantages, the best of both worlds.

**Comment by Seneral** [comment]
You're right, but we don't want to forc this, or? If we still want, we can put the same properties in the node body. But anyway, does work good this way, the node creator has much more flexibility now:)

**Comment by ScriptGeek** [comment]
Yes, the new method is totally optional and properties can still go anywhere, it's all up to the user of the framework.  I'm excited to make some more nodes! :)
