### ISSUE TITLE
gh-pages not orphan

### ISSUE THREAD

**Issue by groud** [Baste-RainGames/Node_Editor#51]
The gh-pages branch has nothing to do with the master branch.
It should a be an orphan branch.

https://help.github.com/articles/creating-project-pages-manually/

**Comment by Seneral** [comment]
I've followed a similar page about creating pages manually, and that did not mention an orphan branch but just said to clone the mster and remove everxthing else from it and add the site related stuff.
I think the only difference is that now there's a link between them I suppose. Can I change that now that I already created the branch?

**Comment by groud** [comment]
I dont think there is a possibility for doing this without deleting the branch.
If you dont mind, I can handle this :)

**Comment by Seneral** [comment]
I did already delete it and now I can't create an orphan branch (in source tree I'm using the terminal):
![screenshot11](https://cloud.githubusercontent.com/assets/12800840/13202628/815c1a7e-d8a1-11e5-8ce4-ba1024ababc6.jpg)
This should be it, right? But neither on the gihub site nor in Source tree I can find that branch...

**Comment by groud** [comment]
Awesome, i think you need to push the initial commit to see it into Github.

**Comment by Seneral** [comment]
How if I can't see the branch? :(

**Comment by groud** [comment]
Well, if you deleted the branch, you have to:

Create the new orphan branch:
`git checkout --oprhan gh-page`
(You 

Delete all files on this branch:
`git rm -rf .`

**Comment by Seneral** [comment]
Tried that too but the only message I got was 
![screenshot12](https://cloud.githubusercontent.com/assets/12800840/13202682/5333237a-d8a3-11e5-87dd-601254598ef6.jpg)
Note I'm back on master

**Comment by groud** [comment]
You forgot the point :)
The point means "current directory"

Get back to gh-pages using:
`git checkout gh-page`
and then continue with the `git rm -rf `. command

**Comment by Seneral** [comment]
Ah, now it works. Any idea how I can add all files in the directory to the commit?
There are a few:)

**Comment by Seneral** [comment]
Hm, ok got it working until the commit. After `git push origin gh-pages` He asked for the name, I entered it, then for the password, and even though I entered it nothing has showed up. nyway, after clicking enter I saw an error, when i tried to checkout gh-pages I saw another error:
![screenshot13](https://cloud.githubusercontent.com/assets/12800840/13202711/8d14bc6a-d8a4-11e5-9890-0976c8d873b7.jpg)
Any idea?

**Comment by groud** [comment]
Can you run : 
`git branch -l`
and paste the result ?

**Comment by Seneral** [comment]
only develop, master (current) and Unity Func feature

**Comment by Seneral** [comment]
But I have a local push now how I named it in the console
It is targeted to the master branch though

**Comment by groud** [comment]
I do not get whet you mean by "local push".
Can you get into the master branch and run 
`git status`

**Comment by Seneral** [comment]
I removed it and did everything all over again. Now I'm here:
![cmdline-orphanbranchcreation](https://cloud.githubusercontent.com/assets/12800840/13202817/433469de-d8a8-11e5-9731-7a1536f18530.gif)
I would enter my name and then password, but this doesn't work (see screens above)

**Comment by Seneral** [comment]
Ok I got it in SourceTree locally. But without entering the password I cannot put it in remote.

**Comment by Seneral** [comment]
Finally! it is online! ;)

**Comment by groud** [comment]
Yes sorry, I forgot one argument in the command line. I think:
`git push -u origin gh-pages`

Awesome !

**Comment by Seneral** [comment]
It did work without, but somehow it didn't even create it locally I think. Anyways, time to move on. Thanks!
