### ISSUE TITLE
First clean Node Editor release

### ISSUE THREAD

**Issue by Seneral** [Baste-RainGames/Node_Editor#54]
Due to the recent change in the repository management, I think it is suited to finally clean themaster branch. We've already moved the developement stuff to their own respective branches, so we can do this without worries. 
To mark the importance of this step, I'll just add a release and milestone to this issue, wish will then be the first (official) one ever.
I've already cleaned a version so far to have removed all current WIP stuff, including the action Node / Unity Func and the state system stuff.

**Comment by Seneral** [comment]
Release can be found [here](https://github.com/Baste-RainGames/Node_Editor/releases/tag/v0.1) :)

**Comment by pmhpereira** [comment]
Yay! Congrats! :D

**Comment by Seneral** [comment]
Btw also congrats everyone to hundred watchers;)
