### ISSUE TITLE
Unity Asset Store

### ISSUE THREAD

**Issue by tqtran7** [Baste-RainGames/Node_Editor#77]
This is not really a bug, more of a wishlist. I came across this project from the forum. I have to say it is impressive and exactly the thing I am looking for. What puzzles me is why it is not in the Unity Asset Store (this is likely the first people go to find things like this!).

**Comment by Seneral** [comment]
This has been brought up before I think but we dcided for that time not to make an asset store product. Obviousl it would mean more work, even if it's free there's more management to do and more resonsibility. But in my opinion it is an option we should consider - when we made yet another stable version, including the merged commits from develop:)
