### ISSUE TITLE
Documentation should have installation section

### ISSUE THREAD

**Issue by tqtran7** [Baste-RainGames/Node_Editor#78]
Someone who is new to Unity may not know how to install this (since it is not in the asset store either). A small and brief section in the documentation on how to incorporate Node Editor could be helpful.

**Comment by Seneral** [comment]
Thanks for the note:) Actually, there's quite a lot of sections I'd like to add but I don't have much time. First priority is merging develop and master, because then we can launch a different documentation that is alot better bu is only for the develop branch. Still needs lots of improvemens but it would be the first steps needed for a better doc... See #46 :)

**Comment by rc1** [comment]
I'd like to know how to install it? :)

**Comment by Seneral** [comment]
Just put the Editor and Node Editor folder into the Assets/Plugins folder and you can access it under Window. If you put it elsewhere it should still work just fine but outputs a warning asking you to change the hardcoded installation path. Pretty simple and straight forward actually;)
Also, make sure you have no errors in your project, else it won't show up under Window.

**Comment by rc1** [comment]
Easy if you know how 😉 . Joking aside, thanks. 

I'm coming up with a series of errors which are no doubt due to my inexperience.

**Comment by Seneral** [comment]
Are you joking now? o.O :)
Anyway, there shouldn't be any errors, especially not on import - if they are, then most likely due to the platform or build target - can you send a picture of them and a description?

**Comment by rc1** [comment]
I have 'em fixed.

This is such an excellent project & useful tool. Can't thank you enough @Seneral and everyone else too. It's one of those things which makes you go: wow, isn't the internet is great.

My observation on the OP's question only (as I'm new-ish to Unity): an *as-basic-as-possible* Unity project repo with Node_Editor may be more useful  as an initial kickstart than installation documentation. 

Writing more comprehensive docs is no small task. Hence I thought I chip in with the quick fix. I hope this does sound like a complaint, criticism or someone suggesting something on an opensource project and not offering to do it. *Erm, maybe that last one...*

**Comment by Seneral** [comment]
Thank you very much for your kind words @rc1 :)
So, what are you proposing exactly? I mean, it simply drag'n'drop into any location in the project and the user will be notified where it has to go (Plugins)... Sure, a file like 'Installation' would be nice, if that's what you're thinking of?
And yep, sure documentation isn't easy but I have to admit I haven't spend as much time into it as I should have:/ It is actually very old but the difference between master and develop is holding me back kinda...

**Comment by rc1** [comment]
Yeah. Perhaps:

- The (develop branch of) Node_Editor  in the `Plugins` 
- A scene that loads a canvas from assets
- A scene with two canvases baked in (perhaps moving a circle on screen?)
- A scene showing the RuntimeNodeEditor / RTCanvasCalculator

**Comment by Seneral** [comment]
Well ok most things are drag and drop and pretty straightforward, or not? I think that should be ok, but installation instructions are no problem.

**Comment by rc1** [comment]
Yeah there super *straightforward*, (i.e. nicely done). But I'm sure how *obvious* they are. Ideally someone shouldn't need to through every folder and file before starting to use the library. It's be better to just open up an example or two and glean the high level picture.

**Comment by Seneral** [comment]
In the new documentation I'm working on there is a section now detailing the Installation process:) I hope  to get the documentation live in the next few weeks...
