### ISSUE TITLE
Having trouble making custom connection types

### ISSUE THREAD

**Issue by pi3butcher** [Baste-RainGames/Node_Editor#79]
I'm having trouble implementing custom connection types. The current documentation seemed quite straightforward and simple, but I keep getting an error.

Basically, I need the output of a node to be a custom component reference which I assign in the inspector.

1) Made Machine Node (assign Machine component in inspector)
![capture](https://cloud.githubusercontent.com/assets/3300071/16396142/4d80d336-3c8b-11e6-8874-1f4b7b2ecbb5.PNG)

2) Created ITypeDeclaration Interface
`
using UnityEngine;
using System;

public interface ITypeDeclaration {

	string name { get; }
	Color col { get; }
	string InputKnob_TexPath { get; }
	string OutputKnob_TexPath { get; }
	Type Type { get; }
}
`

3) Created MachineType
`
using UnityEngine;
using System;

public class MachineType : ITypeDeclaration {

	public string name { get { return "Machine";  } }
	public Color col { get { return Color.cyan; } }
	public string InputKnob_TexPath  { get { return "Textures/In_Knob.png";  } }
	public string OutputKnob_TexPath { get { return "Textures/Out_Knob.png"; } }
	public Type Type { get { return typeof(Machine); } }
}
`

4) In my MachineNode Create method, I have this line:
`
node.CreateOutput("Machine", "Machine");
`

5) I get this error:
![capture](https://cloud.githubusercontent.com/assets/3300071/16396386/77dfebe8-3c8c-11e6-9117-15e4c8ad8c0a.PNG)

Maybe I'm misunderstanding this completely, but is it possible to do what I'm trying to do? Thanks ahead for the help!

**Comment by Seneral** [comment]
Hi,
first, you don't need (must not) create the ITypeDeclaration (yourself). The documentation is in one regard outdated, as it refers to the master branch. There were changes so it does not fully apply to the develop branch:/ Though a way improved documentation is waiting to be published once the merge of master and develop is performed:)
For your problem, you need to extend IConnectionTypeDeclaration. It's essentially the same but names have changed. For a detailed overview, take a look at [ConnectionTypes.cs in the master branch](https://github.com/Baste-RainGames/Node_Editor/blob/develop/Node_Editor/Framework/ConnectionTypes.cs). At the very bottom, you see the new IConnectionTypeDeclaration and the default float type. 

Everything else of your code seems fine:)

**Comment by pi3butcher** [comment]
Ahh, you're the man - thanks for the quick replies! :D

**Comment by Seneral** [comment]
No problem, thanks:)

**Comment by oxi-dev0** [comment]
In the new version, where are the ITypeDeclarations and the types declared?
