### ISSUE TITLE
Example or more thorough documentation regarding events anywhere?

### ISSUE THREAD

**Issue by pi3butcher** [Baste-RainGames/Node_Editor#81]
I'm using the Node Editor as tool to modify/move/add/remove components in the Editor (not in play mode). I'd imagine that I want to use the NodeEditorCallbacks class and not the NodeEditorCallbackReceiver one. I understand how to implement the second method, but not the prior. Any examples anywhere?

**Comment by Seneral** [comment]
You need to build a 3rd editor script anywhere that subscribes to these events. So you'd do `NodeEditorFramework.NodeEditorCallbacks.OnNodeMove += MyCallbackMethod`
Hope that helps!

**Comment by pi3butcher** [comment]
I'm sorry, I can't seem to get it working, here's my code:

![image](https://cloud.githubusercontent.com/assets/3300071/16459205/109af0d0-3df0-11e6-8003-323bb8118c25.png)

I added a Debug.Log in the OnEnable function, but got nothing. o.0

**Comment by pi3butcher** [comment]
Finally got it working but adding this line:

`[CustomEditor(typeof(MachineNode))]`

However, it keeps adding the connection OnEnable (duh). I added a static bool to track whether or not I've subscribed to the delegate. It appears to work fine! Or would there be a better place to subscribe?

**Comment by Seneral** [comment]
Sorry, was unavaiable. Yes for it to execute you need to make it a custom editor (in this case).

For delegates, I tend to first unsubscribe (-=) and then subscribe (+=). If you haven't subsribed before it will do nothing but if you did you won't have duplicate subscribers:)

**Comment by pi3butcher** [comment]
No worries! And ahh got it thanks! :D
