### ISSUE TITLE
Unable to build after cloning

### ISSUE THREAD

**Issue by rc1** [Baste-RainGames/Node_Editor#85]
Hello.

Using a fresh clone of the develop branch into a new unity project, I cannot build this. I am on OSX with Unity 5.3.5f1.

There error is on `HotkeyAttribute` and `EventHandlerAttribute`.

![screen shot 2016-07-21 at 15 14 09](https://cloud.githubusercontent.com/assets/166915/17025880/d4f531fe-4f55-11e6-836e-b38ed7ddf120.png)

The quite fix to get it to compile is to make `priority` read/write by removing the `private` keyword for `priority` in the implementation of both `HotkeyAttribute` and `EventHandlerAttribute`. However I don't know what the consequences are. I am just trying out Node_Editor. 

Cheers,
Ross

**Comment by Seneral** [comment]
Yep, that should be no problem. I didn't know that this is handled differently on some platforms... best to go that way then:) Maybe it's the Unity version (I'm still at 5.3.4) but for me it works fine on windows. What is your build target at?
Seneral

**Comment by rc1** [comment]
Build target is "PC, Mac & Linux" at the moment. I'm downloading the latest Unity just now. Thanks

**Comment by Seneral** [comment]
Well, I don't have the latest unity to test, that is;) I think your version, 5.3.5, is the latest, so don't worry.
Ok so it is likely related to OSX, seems that library of mono does handle optional named parameters differently. So a simple fix like yours will do:) Thanks for bringing this up!

**Comment by DennyScott** [comment]
Hey Seneral, I'm having the same issue on Windows, but Im on version 5.3.6.. Build Target is PC.

**Comment by Seneral** [comment]
Ok, @ChicK00o did create a fix for this in #84 which we're preparing for merge right now:)
