### ISSUE TITLE
Namespace on  [PopupMenu] and [GenericMenu]

### ISSUE THREAD

**Issue by AncientPixel** [Baste-RainGames/Node_Editor#9]
Could you add [PopupMenu] and [GenericMenu] to a namespace as they are causing clashes problems with [AstarPathfindingProject] from http://arongranberg.com/astar/.
I would suggest [NodeEditorFramework.Design] as Unity uses a common namespace name like [UI] in their namespaces.

**Comment by Seneral** [comment]
Addressed that here: da768af2ea539968f7acf3d9e16cbc191710cd05
I put the utilities in either NodeEditorFramework.Utilities or NodeEditorFramework.Resources, and now no Node Editor class should be outside of the NodeEditorFramework namespace:)
