### ISSUE TITLE
re-positioning nodes does not move hitbox.

### ISSUE THREAD

**Issue by pollend** [Baste-RainGames/Node_Editor#99]
![image](https://cloud.githubusercontent.com/assets/854359/18696812/b86c5116-7f70-11e6-9677-1470add8ac8d.png)

**Comment by Seneral** [comment]
Can you tell me how you saved the cancas? 
This is a rare save Bug so I'd like to track it down.  You can just reopen the Canvas and it should be gone;)

**Comment by pollend** [comment]
I was using setPosition but InputKnob (x) with the index seems to resolve this.

**Comment by Seneral** [comment]
Oh, I thought you meant the node, not the knob. There is indeed an error in the save system I believe to have fixed that sometimes make nodes duplicate where one node was functional and one would basically 'sit' there without receiving input.
Anyway, yeah the node knob position need atleast one redraw to appear correctly, can be observed when opening the canvas without the mouse cursor in it.
Not crucial though, maybe a Repaint command correctly set will fix this;)
